
nextcloud:

  onlyoffice_namespace: onlyoffice
  onlyoffice_service: documentserver
  onlyoffice_port: 8888
  onlyoffice_public_url: https://docserv-onlyoffice.apps.dev.okd.hpda.ulb.ac.be/

  apps:
    onlyoffice:
      enabled: yes
      json_config:
        DocumentServerInternalUrl: "http://documentserver.onlyoffice.svc.cluster.local:8888"
        DocumentServerUrl: "https://docserv-onlyoffice.apps.dev.okd.hpda.ulb.ac.be/"
        StorageUrl: "https://apache"
        jwt_secret: I8RJPo8sLlRQ39Bqca6SJ3RKri82452v
    theming:
      json_config:
        name: MyCloud ULB (DEV INSTANCE TEST)
    files_antivirus:
      json_config:
        av_mode: "daemon"
        av_host: "clamav"
        av_port: "3310"

    spreed:
      json_config:
        signaling_servers:
          servers:
            - server: wss://mycloud-talk.ulb.be/
              verify: yes
        turn_servers:
          - scheme: turn
            server: mycloud-talk.ulb.be:8443
            secret: 319e264dd273c3d19fdfc5fbc4f4d997edffd5825aedcd13798f64eac286a64a
            protocols: tcp

