
nextcloud:

  onlyoffice_namespace: onlyoffice
  onlyoffice_service: documentserver
  onlyoffice_port: 8888
  onlyoffice_public_url: https://docserv-onlyoffice.apps.dev.okd.hpda.ulb.ac.be/

  apps:
    onlyoffice:
      enabled: yes
      json_config:
        DocumentServerInternalUrl: "http://documentserver.onlyoffice.svc.cluster.local:8888"
        DocumentServerUrl: "https://docserv-onlyoffice.apps.dev.okd.hpda.ulb.ac.be/"
        StorageUrl: "https://apache"
        jwt_secret: I8RJPo8sLlRQ39Bqca6SJ3RKri82452v
    theming:
      json_config:
        name: MyCloud ULB (DEV INSTANCE TEST)
    spreed:
      json_config:
        signaling_servers:
          secret: c063f274a0d9201966b1131148ec013eea8fada1e751406e0d3bfde2cc367b4a
    files_antivirus:
      json_config:
        av_mode: "socket"
        av_host: "clamav"
        av_port: "3310"
