version: "3.8"


x-common-env: &common-env
  ALLOW_EMPTY_PASSWORD: "no"
  MARIADB_GALERA_CLUSTER_NAME: "nextcloud-cluster"
  MARIADB_GALERA_CLUSTER_ADDRESS: "gcomm://mariadb1,mariadb2,mariadb3"
  MARIADB_EXTRA_FLAGS: >-
    --wsrep-sync-wait=3
    --transaction-isolation=READ-COMMITTED
    --sql-mode=NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    --expire-logs-days=3

services:
  mariadb1:
    image: bitnami/mariadb-galera:11.4.7
    networks:
      - galera_net
    env_file:
      - ./mariadb-galera/.env
    environment:
      <<: *common-env
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "yes"
      MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP: "yes"
      MARIADB_GALERA_NODE_NAME: "mariadb1"
    volumes:
      - mariadb1_data:/bitnami/mariadb
    configs:
      - source: mariadb_custom_cnf
        target: /etc/mysql/conf.d/custom.cnf
    deploy:
      placement:
        constraints:
          - node.hostname == node1

  mariadb2:
    image: bitnami/mariadb-galera:11.4.7
    networks:
      - galera_net
    env_file:
      - ./mariadb-galera/.env
    environment:
      <<: *common-env
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "no"
      MARIADB_GALERA_NODE_NAME: "mariadb2"
    volumes:
      - mariadb2_data:/bitnami/mariadb
    configs:
      - source: mariadb_custom_cnf
        target: /etc/mysql/conf.d/custom.cnf
    deploy:
      placement:
        constraints:
          - node.hostname == node2

  mariadb3:
    image: bitnami/mariadb-galera:11.4.7
    networks:
      - galera_net
    env_file:
      - ./mariadb-galera/.env
    environment:
      <<: *common-env
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "no"
      MARIADB_GALERA_NODE_NAME: "mariadb3"
    volumes:
      - mariadb3_data:/bitnami/mariadb
    configs:
      - source: mariadb_custom_cnf
        target: /etc/mysql/conf.d/custom.cnf
    deploy:
      placement:
        constraints:
          - node.hostname == node3

networks:
  galera_net:
    driver: overlay

volumes:
  mariadb1_data:
  mariadb2_data:
  mariadb3_data:

configs:
  mariadb_custom_cnf:
    external: true

