x-common-env: &common-env
  ALLOW_EMPTY_PASSWORD: "no"
  MARIADB_GALERA_CLUSTER_NAME: nextcloud-cluster
  MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://mariadb1,mariadb2,mariadb3
  MARIADB_EXTRA_FLAGS: >-
    --wsrep-sync-wait=3
    --transaction-isolation=READ-COMMITTED
    --sql-mode=NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    --expire-logs-days=3


services:


  nextcloud:
    # build:
    #   context: ./php-fpm/
    #   dockerfile: Dockerfile
    image: registry.gitlab.ulb.be/pole-techno/nextcloud-a6k/php-fpm:main
    pull_policy: always
    container_name: nextcloud
    # depends_on:
    #   - mariadb1
    #   - redis
    networks:
      - galera_net
    volumes:
      # - nextcloud_data:/srv/data
      - ./php-fpm/files/nc_config.php:/var/www/html/config/k8s.config.php:ro
      - ./php-fpm/files/php.ini:/etc/php/cur/fpm/conf.d/99-k8s.ini:ro
      # - ./config:/var/www/html/config
  
  nextcloud-cron:
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./nextcloud.env
      - ./db.env
    volumes:
      - ./app:/var/www/html
      - ./files:/var/www/html/data
      - ./config:/var/www/html/config
    entrypoint: /cron.sh
    depends_on:
      - nextcloud

  notify-push:
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
    command:
      - /usr/local/bin/notify_push
      - --glob-config
      - --allow-self-signed
      - --
      - /var/www/html/config/config.php
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "7867"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    volumes:
      - nextcloud_data:/srv/data
      - ./php-fpm/files/nc_config.php:/var/www/html/config/k8s.config.php:ro
    environment:
      - ALLOW_SELF_SIGNED=true
    networks:
      - galera_net

  clamav:
    image: ghcr.io/mailu/clamav:1.9.50
    restart: always

  setup:
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
    entrypoint: ["/scripts/setup.sh"]
    networks:
      - galera_net
    env_file:
      - ./mariadb-galera/.env
    # environment:
    #   DBPASS: secret
    #   NCADMINPASS: youradminpass
    depends_on:
      - mariadb1
    volumes:
      - nextcloud_data:/srv/data
      - ./php-fpm/scripts:/scripts
      # - ./config:/var/www/html/config
    restart: "no"

  apache:
    # build:
    #   context: ./apache/
    #   dockerfile: Dockerfile
    image: registry.gitlab.ulb.be/pole-techno/nextcloud-a6k/apache:main
    pull_policy: always
    volumes:
       - ./tls.crt:/ssl/tls.crt
       - ./tls.key:/ssl/tls.key
    ports:
      - "8443:8443"
    networks:
      - galera_net


  mariadb1:
    image: bitnami/mariadb-galera:11.4.7
    restart: unless-stopped
    networks:
      - galera_net
    container_name: mariadb1
    env_file:
      - ./mariadb-galera/.env
    environment:
      <<: *common-env
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: no
      # MARIADB_GALERA_CLUSTER_BOOTSTRAP: yes
      MARIADB_GALERA_NODE_NAME: mariadb1
    volumes:
      - mariadb1_data:/bitnami/mariadb
      - ./conf.d:/bitnami/mariadb/conf

  mariadb2:
    image: bitnami/mariadb-galera:11.4.7
    restart: unless-stopped
    networks:
      - galera_net
    container_name: mariadb2
    env_file:
      - ./mariadb-galera/.env
    environment:
      <<: *common-env
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: no
      MARIADB_GALERA_NODE_NAME: mariadb2
    volumes:
      - mariadb2_data:/bitnami/mariadb
      - ./conf.d:/bitnami/mariadb/conf

  mariadb3:
    image: bitnami/mariadb-galera:11.4.7
    restart: unless-stopped
    networks:
      - galera_net
    container_name: mariadb3
    env_file:
      - ./mariadb-galera/.env
    environment:
      <<: *common-env
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: no
      MARIADB_GALERA_NODE_NAME: mariadb3
    volumes:
      - mariadb3_data:/bitnami/mariadb
      - ./conf.d:/bitnami/mariadb/conf


  proxysql:
    build:
      context: ./proxysql/
      dockerfile: Dockerfile
    container_name: proxysql
    env_file:
      - ./mariadb-galera/.env
    ports:
      - "6033:6033"  # MySQL client-facing port
      - "6032:6032"  # Admin port
    volumes:
      - ./proxysql/proxysql.cnf.template:/etc/proxysql.cnf.template:ro
    # healthcheck:
    #   test: [ "CMD", "bash", "/probe.sh", "readiness" ]
    #   interval: 15s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 30s
    restart: always
    networks:
      - galera_net

  # redis:
  #   image: redis:alpine
  #   restart: always

  redis-cluster-1:
    image: bitnami/redis-cluster:7.0
    environment:
      # - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-1
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - galera_net

  redis-cluster-2:
    image: bitnami/redis-cluster:7.0
    environment:
      # - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-2
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - galera_net

  redis-cluster-3:
    image: bitnami/redis-cluster:7.0
    environment:
      # - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-3
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - galera_net

  

volumes:
  mariadb1_data:
  mariadb2_data:
  mariadb3_data:
  redis:
  nextcloud_data:

networks:
  galera_net:
    driver: bridge
